"""empty message

Revision ID: 37bd0e5d706e
Revises: 2bb10725a9e3
Create Date: 2021-08-04 19:03:12.453220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bd0e5d706e'
down_revision = '2bb10725a9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('postImage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'postImage')
    # ### end Alembic commands ###
