"""empty message

Revision ID: d07b02be37cf
Revises: d834a762b95e
Create Date: 2021-07-29 00:04:02.882253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07b02be37cf'
down_revision = 'd834a762b95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', sa.String(), nullable=True))
    op.add_column('users', sa.Column('handle', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'status')
    op.drop_column('users', 'handle')
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
